package org.jth.templates;

import java.util.Map;
import java.util.Date;

public interface EmploymentTemplateHelper {
    
    public int insertUser(String uniqueIV);
    
    public Map<String, String> insertData(String processing_detail,
                                          Integer update_record_id,
                                          String unique_identifier,
                                          Date dateofbirth,
                                          String postalcode,
                                          Boolean registration_in_employment_intervention,
                                          String a_referrral_to,
                                          Languages language_of_service,
                                          Languages official_language_pref,
                                          String type_of_institution_where_client_recieved_service,
                                          String reffered_by,
                                          Date referral_date,
                                          String employment_status,
                                          String education_status,
                                          String occupation_in_canada,
                                          String intended_occupation,
                                          String intervention_type,
                                          String longtermintervention_recieved,
                                          String longtermintervention_status,
                                          String longtermintervention_reason_leaving,
                                          Date longtermintervention_start_date,
                                          Date longtermintervention_end_date,
                                          String longtermintervention_size_of_employer,
                                          String longterminvervention_placement_was,
                                          String longtermintervention_hours_per_week,
                                          String longtermintervention_client_met_mentor_regularly_at,
                                          Integer longtermintervention_avg_hours_per_week_in_contact_with_mentor,
                                          String longtermintervention_profession_which_service_was_recieved,
                                          Boolean essentialskill_and_aptitudetraining_recieved_as_part_of_service,
                                          Boolean computer_skills,
                                          Boolean document_use,
                                          Boolean interpersonal_skills_and_workplace_culture,
                                          Boolean leadership_training,
                                          Boolean numeracy,
                                          String shorttermintervention_service_required,
                                          Date shorttermintervention_date,
                                          String shorttermintervention_service_required2,
                                          Date shorttermintervention_date2,
                                          String shorttermintervention_service_required3,
                                          Date shorttermintervention_date3,
                                          String shorttermintervention_service_required4,
                                          Date shorttermintervention_date4,
                                          String shorttermintervention_service_required5,
                                          Date shorttermintervention_date5,
                                          Boolean support_services_recieved,
                                          Boolean care_for_newcomer_children,
                                          String child1_age,
                                          String child1_type_of_care,
                                          String child2_age,
                                          String child2_type_of_care,
                                          String child3_age,
                                          String child3_type_of_care,
                                          String child4_age,
                                          String child4_type_of_care,
                                          String child5_age,
                                          String child5_type_of_care,
                                          Boolean transportation,
                                          Boolean provisions_for_disabilities,
                                          Boolean translation,
                                          Languages between1,
                                          Languages and1,
                                          Boolean interpretation,
                                          Languages between2,
                                          Languages and2,
                                          Boolean crisis_counselling,
                                          Integer time_spent_with_client_addressing_employment_needs_hours,
                                          Integer time_spent_with_client_addressing_employment_needs_minutess,
                                          String reason_for_update);
    
}