package org.jth.templates.fieldoptions;

public enum InstitutionType {
    SETTLEMENT_SERVICE_PROVIDER,
    PUBLIC_LIBRARY,
    ELEMENTARY_SCHOOL,
    SECONDARY_SCHOOL,
    POST_SECONDARY_INSTITUTION,
    HEALTHCARE_INSTITUTION,
    COMMUNITY_CENTRE_OR_NEIGHBOURHOOD_HOUSE,
    EMPLOYMENT_AGENCY,
    THE_CLIENTS_HOME,
    THE_CLIENTS_PLACE_OF_EMPLOYMENT,
    A_PUBLIC_SPACE,
    PORT_OF_ENTRY,
    ONLINE,
    NOT_FOR_PROFIT_ORGANIZATION,
}
