package org.jth.templates.fieldoptions;

public enum ReferredOptions {
    COMMUNITY_CENTRE_OR_LIBRARY,
    EMPLOYER_OR_COWORKER,
    ETHNIC_OR_RELIGIOUS_ORGANIZATION,
    FAMILY_OR_FRIENDS,
    CANADIAN_GOVERNMENT_AGENCY,
    GOVERNMENT_PUBLICATION_OR_BROCHURE_OR_WEBSITE,
    IMMIGRATION_CONSULTANT_OR_LAWYER,
    INTERNAL_TO_MY_ORGANIZATION,
    NONGOVERNMENTAL_NEWSPAPER_OR_MEDIA_OR_PUBLICATION_OR_BROCHURE_OR_WEBSITE,
    INCANADA_ORIENTATION_SESSION,
    OVERSEAS_ORIENTATION_SESSION,
    OTHER_SETTLEMENT_SERVICE_PROVIDER,
    SCHOOL,
    NOT_REFERRED,
}
